server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

spring:
  cloud:
    gateway:
      routes:
        - id: post-service
          uri: http://localhost:8081/
          predicates:
            - Path=/post-service/**
          filters:
            - AuthorizationHeaderFilter
        - id: chatting-service
          uri: http://localhost:8082/
          predicates:
            - Path=/chatting-service/**
          filters:
            - AuthorizationHeaderFilter